
// Try catch  -  Error handling
let a = 10;
console.log(a/b)

console.log("hello")


try {
    
} catch (error) {
    
    
}